---
- name: Install Nginx
  hosts: web_servers
  become: yes  # Required for using yum and service modules
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: absent
        purge: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
